version: '3'

tasks:
  default:
    deps: ["build"]
  install:
    deps: ["build"]
    cmds:
      - cp -v ./hexai-lsp ~/go/bin/
      - cp -v ./hexai ~/go/bin/
  run:
    deps: ["dev"]
    cmds:
      - go run cmd/hexai-lsp/main.go
  build:
    deps: ["build-hexai-lsp", "build-hexai-cli"]
  build-hexai-lsp:
    cmds:
      - go build -o hexai-lsp cmd/hexai-lsp/main.go
  build-hexai-cli:
    cmds:
      - go build -o hexai cmd/hexai/main.go
  dev:
    deps: ["test", "vet", "lint"]
    cmds:
      - go build -race -o hexai-lsp cmd/hexai-lsp/main.go
      - go build -race -o hexai cmd/hexai/main.go
  run-cli:
    deps: ["dev"]
    cmds:
      - echo 'test' | go run cmd/hexai/main.go
  test:
    cmds:
      - go clean -testcache
      - go test -v ./... 
  vet:
    cmds:
      - go vet ./...
  lint:
    cmds:
      - golangci-lint run
  dev-install:
    cmds:
      - go install golang.org/x/tools/gopls@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
